-- AlterEnum
BEGIN;
CREATE TYPE "AuditAction_new" AS ENUM ('USER_CREATED', 'USER_UPDATED', 'PASSWORD_CHANGED', 'PASSWORD_RESET_REQUESTED', 'LOGIN', 'LOGOUT', 'LEAVE_SUBMITTED', 'LEAVE_APPROVED', 'LEAVE_REJECTED', 'LEAVE_CANCELLED', 'BALANCE_ADJUSTED', 'EXPENSE_SUBMITTED', 'EXPENSE_APPROVED', 'EXPENSE_REJECTED', 'EXPENSE_REIMBURSED', 'DOCUMENT_UPLOADED', 'DOCUMENT_DELETED', 'LEAVE_DELETED', 'EXPENSE_DELETED', 'REVIEW_CYCLE_CREATED', 'REVIEW_CYCLE_OPENED', 'REVIEW_CYCLE_EVALUATION_OPENED', 'REVIEW_CYCLE_CLOSED', 'REVIEW_GOALS_SET', 'REVIEW_SUBMITTED', 'REVIEW_ACKNOWLEDGED', 'REVIEW_REOPENED', 'PROBATION_CONFIRMED', 'PROBATION_EXTENDED', 'PROBATION_NOT_CONFIRMED', 'TIME_ENTRY_SUBMITTED', 'TIME_ENTRY_APPROVED', 'TIME_ENTRY_REJECTED', 'TIME_ENTRY_DELETED', 'TIME_ENTRY_UNLOCKED', 'REWARD_CYCLE_CREATED', 'REWARD_CYCLE_APPROVED', 'REWARD_CYCLE_PAID', 'REWARD_CYCLE_CLOSED', 'REWARD_ALLOCATION_SAVED', 'REWARD_ALLOCATION_APPROVED', 'REWARD_ALLOCATION_PAID', 'REWARD_ALLOCATION_CANCELLED', 'WORK_PASS_CREATED', 'WORK_PASS_UPDATED', 'WORK_PASS_DELETED', 'BLACKOUT_CREATED', 'BLACKOUT_UPDATED', 'BLACKOUT_DELETED', 'EMPLOYMENT_LETTER_GENERATED', 'CONFIRMATION_LETTER_GENERATED', 'LETTER_REVIEWED', 'LETTER_SIGNED', 'LETTER_REJECTED', 'LETTER_SENT', 'LETTER_REMINDER_SENT', 'CONFIRMATION_DATE_SET', 'USER_OFFBOARDED', 'APPROVALS_REASSIGNED', 'DIRECT_REPORTS_REASSIGNED', 'SESSION_REVOKED', 'SETTING_UPDATED', 'STATUTORY_RULES_CREATED', 'STATUTORY_RULES_VERIFIED', 'LEAVE_REVERSED', 'EXPENSE_REVERSED', 'TIME_ENTRY_REVERSED', 'REVIEW_CYCLE_REVERSED', 'PERFORMANCE_REVIEW_REVERSED', 'REWARD_CYCLE_REVERSED', 'REWARD_ALLOCATION_REVERSED', 'EMPLOYMENT_LETTER_REVERSED', 'LEARNING_LOCKOUT_REVERSED', 'PAYROLL_EXPORTED', 'EXPENSE_EXPORTED', 'RATINGS_EXPORTED', 'DOCUMENT_VIEWED');
ALTER TABLE "AuditLog" ALTER COLUMN "action" TYPE "AuditAction_new" USING ("action"::text::"AuditAction_new");
ALTER TYPE "AuditAction" RENAME TO "AuditAction_old";
ALTER TYPE "AuditAction_new" RENAME TO "AuditAction";
DROP TYPE "public"."AuditAction_old";
COMMIT;

-- AlterTable
ALTER TABLE "Document" DROP COLUMN "s3Key";

-- AlterTable
ALTER TABLE "EmploymentLetter" DROP COLUMN "driveFileId",
DROP COLUMN "driveWebViewLink";

-- AlterTable
ALTER TABLE "ExpenseReceipt" DROP COLUMN "s3Key";

-- AlterTable
ALTER TABLE "LeaveRequest" DROP COLUMN "attachmentKey";

-- AlterTable
ALTER TABLE "User" DROP COLUMN "folderArchivedAt";

-- CreateIndex
CREATE INDEX "Document_blobId_idx" ON "Document"("blobId");

-- CreateIndex
CREATE INDEX "EmploymentLetter_blobId_idx" ON "EmploymentLetter"("blobId");

-- CreateIndex
CREATE INDEX "ExpenseReceipt_blobId_idx" ON "ExpenseReceipt"("blobId");

-- CreateIndex
CREATE INDEX "LeaveRequest_attachmentBlobId_idx" ON "LeaveRequest"("attachmentBlobId");

-- CreateIndex
CREATE INDEX "LetterTemplate_blobId_idx" ON "LetterTemplate"("blobId");

