import { requireCapability } from '@/lib/dal'
import { getLetterTemplates } from '@/actions/letterTemplates'
import { LetterTemplateManager } from '@/components/admin/LetterTemplateManager'

export default async function LetterTemplatesPage() {
  await requireCapability('letters.write')
  const { rows, missingTypes, availableMergeFields } = await getLetterTemplates()

  return (
    <div className="space-y-6">
      <div>
        <h1 className="text-2xl font-bold">Letter Templates</h1>
        <p className="text-muted-foreground">
          Employment and confirmation letters are generated by filling a fillable PDF. Upload one
          per letter type; the app fills its form fields with the employee&apos;s details and
          flattens the result so the delivered letter cannot be edited.
        </p>
        <p className="mt-2 text-sm text-muted-foreground">
          Templates used to be Google Docs referenced by an environment variable, so changing one
          needed Google access and a redeploy. They are now stored here.
        </p>
      </div>

      <LetterTemplateManager
        rows={rows}
        missingTypes={missingTypes as ('EMPLOYMENT' | 'CONFIRMATION')[]}
        availableMergeFields={availableMergeFields}
      />
    </div>
  )
}
