/**
 * Install the built-in placeholder letter templates.
 *
 *   npm run letters:placeholder-templates
 *
 * Letters are generated by filling a fillable PDF. Until HR uploads real company
 * stationery there is no template, so letter records are created without a PDF.
 * This installs a plain, unbranded but fully working template for both letter
 * types so the workflow can be used and demonstrated immediately.
 *
 * Safe to re-run. It will not overwrite a real template that HR has uploaded —
 * only a previous placeholder.
 *
 * The same thing is available in the UI at Admin → Letter Templates.
 */
import { PrismaClient } from '../src/generated/prisma/client'
import { PrismaPg } from '@prisma/adapter-pg'
import { createHash } from 'node:crypto'
import { PDFDocument, StandardFonts, rgb } from 'pdf-lib'

const adapter = new PrismaPg({ connectionString: process.env.DATABASE_URL! })
const prisma = new PrismaClient({ adapter })

type LetterType = 'EMPLOYMENT' | 'CONFIRMATION'

/**
 * Kept in step with `buildPlaceholderTemplate` in src/lib/letterPdf.ts.
 *
 * Duplicated rather than imported because this script runs outside Next and
 * `src/lib/letterPdf.ts` is marked `server-only`, which throws when imported
 * from a plain Node process.
 */
async function buildPlaceholderTemplate(type: LetterType): Promise<Buffer> {
  const pdf = await PDFDocument.create()
  const page = pdf.addPage([595.28, 841.89]) // A4
  const font = await pdf.embedFont(StandardFonts.Helvetica)
  const bold = await pdf.embedFont(StandardFonts.HelveticaBold)
  const form = pdf.getForm()

  const left = 72
  const right = 595.28 - 72
  let y = 780

  const grey = rgb(0.42, 0.42, 0.45)
  const black = rgb(0.1, 0.1, 0.12)

  function text(value: string, opts: { size?: number; bold?: boolean; color?: typeof black } = {}) {
    page.drawText(value, {
      x: left,
      y,
      size: opts.size ?? 11,
      font: opts.bold ? bold : font,
      color: opts.color ?? black,
    })
  }

  function field(name: string, label: string, opts: { width?: number } = {}) {
    page.drawText(label, { x: left, y, size: 8, font, color: grey })
    y -= 15
    const box = form.createTextField(name)
    box.setText('')
    box.addToPage(page, {
      x: left,
      y: y - 3,
      width: opts.width ?? right - left,
      height: 18,
      borderWidth: 0.5,
      borderColor: rgb(0.8, 0.8, 0.84),
      backgroundColor: rgb(0.98, 0.98, 0.99),
      font,
    })
    y -= 26
  }

  const title = type === 'EMPLOYMENT' ? 'LETTER OF EMPLOYMENT' : 'LETTER OF CONFIRMATION'
  text(title, { size: 16, bold: true })
  y -= 12
  page.drawLine({
    start: { x: left, y },
    end: { x: right, y },
    thickness: 0.75,
    color: rgb(0.8, 0.8, 0.84),
  })
  y -= 24
  text('PLACEHOLDER TEMPLATE — replace with approved company stationery', {
    size: 8,
    color: grey,
  })
  y -= 28

  field('company', 'Company')
  field('today', 'Date')
  y -= 6
  field('fullName', 'Employee name')
  field('employeeNumber', 'Employee ID', { width: 220 })
  field('email', 'Email')
  field('position', 'Position')
  field('department', 'Department')
  field('country', 'Country', { width: 220 })
  field('startDate', 'Start date', { width: 220 })

  if (type === 'EMPLOYMENT') {
    field('probationEndDate', 'Probation end date', { width: 220 })
  } else {
    field('confirmationDate', 'Confirmation date', { width: 220 })
  }

  y -= 10
  text(
    type === 'EMPLOYMENT'
      ? 'We are pleased to confirm your employment on the terms recorded above.'
      : 'We are pleased to confirm that you have successfully completed your probation period.',
    { size: 10 },
  )
  y -= 40
  text('Signed for and on behalf of the company', { size: 8, color: grey })
  y -= 46 // room for the stamped signature image
  field('approvingOfficerName', 'Name of signing officer', { width: 260 })

  return Buffer.from(await pdf.save())
}

async function storeBlob(data: Buffer): Promise<string> {
  const sha256 = createHash('sha256').update(data).digest('hex')

  const existing = await prisma.fileBlob.findUnique({ where: { sha256 }, select: { id: true } })
  if (existing) {
    await prisma.fileBlob.update({
      where: { id: existing.id },
      data: { refCount: { increment: 1 } },
    })
    return existing.id
  }

  const created = await prisma.fileBlob.create({
    data: {
      sha256,
      data: new Uint8Array(data),
      mimeType: 'application/pdf',
      fileSize: data.byteLength,
      refCount: 1,
    },
    select: { id: true },
  })
  return created.id
}

async function main() {
  for (const type of ['EMPLOYMENT', 'CONFIRMATION'] as LetterType[]) {
    const existing = await prisma.letterTemplate.findUnique({ where: { type } })

    if (existing && !existing.isPlaceholder) {
      console.log(`${type}: real template already uploaded (${existing.fileName}) — left alone.`)
      continue
    }

    const bytes = await buildPlaceholderTemplate(type)

    // Read the field names back out of the PDF we just built, so what is
    // recorded is what is actually in the file rather than what we intended.
    const fieldNames = (await PDFDocument.load(bytes))
      .getForm()
      .getFields()
      .map(f => f.getName())

    const blobId = await storeBlob(bytes)
    const fileName = `${type === 'EMPLOYMENT' ? 'Employment' : 'Confirmation'} Letter (placeholder).pdf`

    await prisma.letterTemplate.upsert({
      where: { type },
      create: { type, blobId, fileName, fieldNames, isPlaceholder: true },
      update: { blobId, fileName, fieldNames, isPlaceholder: true },
    })

    if (existing && existing.blobId !== blobId) {
      await prisma.fileBlob
        .delete({ where: { id: existing.blobId } })
        .catch(() => {
          /* still referenced — leave it */
        })
    }

    console.log(
      `${type}: placeholder installed (${(bytes.byteLength / 1024).toFixed(1)} KB, ` +
        `${fieldNames.length} fields: ${fieldNames.join(', ')})`,
    )
  }
}

main()
  .catch(err => {
    console.error(err)
    process.exit(1)
  })
  .finally(() => prisma.$disconnect())
