/**
 * Install the built-in placeholder letter templates.
 *
 *   npm run letters:placeholder-templates
 *
 * Letters are generated by filling a fillable PDF. Until HR uploads real company
 * stationery there is no template, so letter records are created without a PDF.
 * This installs a plain, unbranded but fully working template for both letter
 * types so the workflow can be used and demonstrated immediately.
 *
 * Safe to re-run. It will not overwrite a real template that HR has uploaded —
 * only a previous placeholder.
 *
 * The same thing is available in the UI at Admin → Letter Templates.
 */
import { PrismaClient } from '../src/generated/prisma/client'
import { PrismaPg } from '@prisma/adapter-pg'
import { createHash } from 'node:crypto'
import { PDFDocument } from 'pdf-lib'
import { buildPlaceholderTemplate } from '../src/lib/letterTemplate'

const adapter = new PrismaPg({ connectionString: process.env.DATABASE_URL! })
const prisma = new PrismaClient({ adapter })

type LetterType = 'EMPLOYMENT' | 'CONFIRMATION'

/** Minimal inline copy of the storage layer's put(), which is server-only. */
async function storeBlob(data: Buffer): Promise<string> {
  const sha256 = createHash('sha256').update(data).digest('hex')

  const existing = await prisma.fileBlob.findUnique({ where: { sha256 }, select: { id: true } })
  if (existing) {
    await prisma.fileBlob.update({
      where: { id: existing.id },
      data: { refCount: { increment: 1 } },
    })
    return existing.id
  }

  const created = await prisma.fileBlob.create({
    data: {
      sha256,
      data: new Uint8Array(data),
      mimeType: 'application/pdf',
      fileSize: data.byteLength,
      refCount: 1,
    },
    select: { id: true },
  })
  return created.id
}

async function main() {
  for (const type of ['EMPLOYMENT', 'CONFIRMATION'] as LetterType[]) {
    const existing = await prisma.letterTemplate.findUnique({ where: { type } })

    if (existing && !existing.isPlaceholder) {
      console.log(`${type}: real template already uploaded (${existing.fileName}) — left alone.`)
      continue
    }

    const bytes = await buildPlaceholderTemplate(type)

    // Read the field names back out of the PDF we just built, so what is
    // recorded is what is actually in the file rather than what we intended.
    const fieldNames = (await PDFDocument.load(bytes))
      .getForm()
      .getFields()
      .map(f => f.getName())

    const blobId = await storeBlob(bytes)
    const fileName = `${type === 'EMPLOYMENT' ? 'Employment' : 'Confirmation'} Letter (placeholder).pdf`

    await prisma.letterTemplate.upsert({
      where: { type },
      create: { type, blobId, fileName, fieldNames, isPlaceholder: true },
      update: { blobId, fileName, fieldNames, isPlaceholder: true },
    })

    if (existing && existing.blobId !== blobId) {
      await prisma.fileBlob.delete({ where: { id: existing.blobId } }).catch(() => {
        /* still referenced — leave it */
      })
    }

    console.log(
      `${type}: placeholder installed (${(bytes.byteLength / 1024).toFixed(1)} KB, ` +
        `${fieldNames.length} fields: ${fieldNames.join(', ')})`,
    )
  }
}

main()
  .catch(err => {
    console.error(err)
    process.exit(1)
  })
  .finally(() => prisma.$disconnect())
